### ISSUE TITLE
Default io.Writer output

### ISSUE THREAD

**Issue by kempjeng** [francoispqt/onelog#13]
Hello,

Nice project, I'm using it extensively.
I have written a wrapper to go around the `New` function in order to safely initialise the io.Writer interface.

Have you thought about checking for a nil io.Writer interface in the constructor, and applying ioutil.Discard as a deafult?

**Comment by francoispqt** [comment]
Ok, you can submit a pull request or if I find time, will do it for this Friday.

**Comment by kempjeng** [comment]
ok, this is my first pull request and I hope I've done everything correctly :)

**Comment by francoispqt** [comment]
Merged, sorry for the delay :)
