### ISSUE TITLE
color support

### ISSUE THREAD

**Issue by ghost** [francoispqt/onelog#24]
is it possible to output levels in different colors?

**Comment by francoispqt** [comment]
Do you want to make the whole line in color or just the text in the `level` field?

**Comment by ghost** [comment]
just the text in the level field

**Comment by francoispqt** [comment]
You can do it this way using `fatih/color` package:
```go
package main

import (
        "os"

        "github.com/fatih/color"
        "github.com/francoispqt/onelog"
)

func main() {
        onelog.LevelText(onelog.INFO, color.CyanString("INFO"))

        var l = onelog.New(os.Stdout, onelog.ALL)
        l.Info("foo")
}
```

If you want you can submit a PR to add a helper method to onelog to set the colors.

**Comment by francoispqt** [comment]
I'm closing this issue as it can be achieved with the current customisation features.
